# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='file',
            field=models.FileField(blank=True, upload_to='ships/', validators=[warehouse.validators.MaxFileSizeValidator(10242)], verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[warehouse.validators.MaxFileSizeValidator(10242)], verbose_name='avatar'),
        ),
    ]
