# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilisateur'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
