# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20171227_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, verbose_name='actif'),
        ),
    ]
