# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 10:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20170901_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('grade_interior', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note design intérieur')),
                ('grade_exterior', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note design extérieur')),
                ('grade_space', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note espace')),
                ('grade_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note mécanismes')),
                ('grade_weapons', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note armes')),
                ('grade_maneuv', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note manoeuvrabilité')),
            ],
            options={
                'verbose_name': 'appréciation',
            },
        ),
        migrations.RemoveField(
            model_name='ship',
            name='grade_exterior',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='grade_interior',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='grade_maneuv',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='grade_mechanics',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='grade_space',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='grade_weapons',
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='file',
            field=models.FileField(blank=True, upload_to='ships/', validators=[warehouse.validators.MaxFileSizeValidator()], verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.ImageField(blank=True, upload_to='covers/', validators=[warehouse.validators.MaxFileSizeValidator()], verbose_name='vignette'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[warehouse.validators.MaxFileSizeValidator()], verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AddField(
            model_name='review',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='warehouse.Ship', verbose_name='vaisseau'),
        ),
    ]
