# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20170901_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='dwnlds',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de téléchargements'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together=set([('ship', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('ship', 'author')]),
        ),
    ]
