# Generated by Django 2.0.3 on 2018-08-17 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20171227_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='grade_interior',
            new_name='aesthetic_grade',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade_exterior',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade_maneuv',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade_mechanics',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade_space',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade_weapons',
        ),
        migrations.AddField(
            model_name='review',
            name='technic_grade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note design extérieur'),
            preserve_default=False,
        ),
    ]
