# Generated by Django 2.0.3 on 2018-08-19 13:37

from django.db import migrations
import django_resized.forms
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20180817_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=('top', 'left'), force_format=None, keep_meta=True, quality=0, size=(400, 400), upload_to='avatars/', validators=[warehouse.validators.MaxFileSizeValidator(1048576)], verbose_name='avatar'),
        ),
    ]
