# Generated by Django 2.0.3 on 2018-08-23 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20180819_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='aesthetic_grade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note esthétique'),
        ),
        migrations.AlterField(
            model_name='review',
            name='technic_grade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='note technique'),
        ),
    ]
