# Generated by Django 2.0.3 on 2018-11-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20180823_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index', 'id'], 'verbose_name': 'catégorie'},
        ),
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='index'),
        ),
    ]
