# Generated by Django 2.0.3 on 2018-11-10 14:14

import django.core.validators
from django.db import migrations, models
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20181106_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='file',
            field=models.FileField(upload_to='blueprints/', validators=[warehouse.validators.MaxFileSizeValidator(), django.core.validators.FileExtensionValidator(('swbp', 'mps'))], verbose_name='fichier'),
        ),
    ]
