# Generated by Django 2.2.2 on 2019-06-05 17:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20181110_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index', 'id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-added']},
        ),
        migrations.AlterModelOptions(
            name='fileversion',
            options={'verbose_name': 'file version'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='warehouse.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='image',
            field=models.ImageField(blank=True, upload_to='covers/', validators=[warehouse.validators.MaxFileSizeValidator()], verbose_name='cover picture'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='modif',
            field=models.DateTimeField(auto_now=True, verbose_name='date edited'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='pinned'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='slug',
            field=models.SlugField(verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='warehouse.Blueprint'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='warehouse.Blueprint'),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='dwnlds',
            field=models.PositiveIntegerField(default=0, verbose_name='downloads number'),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='file',
            field=models.FileField(upload_to='blueprints/', validators=[warehouse.validators.MaxFileSizeValidator(), django.core.validators.FileExtensionValidator(('swbp', 'mps'))]),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='version number'),
        ),
        migrations.AlterField(
            model_name='review',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='review',
            name='aesthetic_grade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='aesthetic grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='warehouse.Blueprint'),
        ),
        migrations.AlterField(
            model_name='review',
            name='technic_grade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='technic grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=('top', 'left'), force_format=None, keep_meta=True, quality=0, size=(400, 400), upload_to='avatars/', validators=[warehouse.validators.MaxFileSizeValidator(1048576)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(related_name='fans', to='warehouse.Blueprint', verbose_name='favorites'),
        ),
    ]
