# Generated by Django 2.2.13 on 2020-07-05 03:11

from django.db import migrations
import sorl.thumbnail.fields
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20190605_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='covers/', validators=[warehouse.validators.MaxFileSizeValidator()], verbose_name='cover picture'),
        ),
    ]
